pipeline {
    agent any

    stages {

        stage('Crear entorno virtual e instalar dependencias') {
            steps {
                dir('cool_counters') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Linter') {
            steps {
                dir('cool_counters') {
                    sh '''
                        . venv/bin/activate
                        pip install pylint
                        ~/.local/bin/pylint **/*.py || true
                    '''
                }
            }
        }

        stage('Migraciones') {
            steps {
                dir('cool_counters') {
                    sh '''
                        . venv/bin/activate
                        python manage.py migrate
                    '''
                }
            }
        }

        stage('Levantar app') {
            steps {
                dir('cool_counters') {
                    sh '''
                        . venv/bin/activate
                        nohup python manage.py runserver 0.0.0.0:8000 &
                    '''
                }
            }
        }
    }
}