pipeline {
    agent any

    stages {

        stage('Instalar dependencias') {
            steps {
                dir('cool_counters') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Linter') {
            steps {
                dir('cool_counters') {
                    sh 'pip install pylint'
                    sh 'pylint **/*.py || true'
                }
            }
        }

        stage('Migraciones') {
            steps {
                dir('cool_counters') {
                    sh 'python manage.py migrate'
                }
            }
        }

        stage('Levantar app') {
            steps {
                dir('cool_counters') {
                    sh 'python manage.py runserver 0.0.0.0:8000 &'
                }
            }
        }
    }
}