pipeline {
    agent any

    stages {
        stage('Clonar repositorio') {
            steps {
                git 'https://github.com/juliancramos/simple-django-app.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Linter') {
            steps {
                sh 'pip install pylint'
                sh 'pylint **/*.py || true'
            }
        }

        stage('Migraciones') {
            steps {
                sh 'python manage.py migrate'
            }
        }

        stage('Levantar app') {
            steps {
                sh 'python manage.py runserver 0.0.0.0:8000 &'
            }
        }
    }
}